= beliefs.json(5)
Robert Greener
v0.0.1
:doctype: manpage
:manmanual: Concepts Manual
:mansource: beliefs
:man-linkstyle: pass:[blue R < >]

== Name

beliefs.json - A json file used for describing the beliefs used in concept(1).

== Description

The beliefs.json(5) configuration file specifies the beliefs which are used in the concept(1) simulation.

An example beliefs.json.example should have been provided with his application.

This is a valid json file.

The file is a takes the format of repeated entries of:

----
{
  "name": "Belief 1",
  "uuid": "907f0d52-c578-4256-a419-fcc51a1ad959",
  "perceptions": {
    "d0f5efd5-a148-44d1-8490-4cc58e7cb4e1": 0.2
  }
}
----

inside a json array.

== Fields

Each entry in the top-level array contains `name` and (optionally) `uuid` and
`perceptions`.

*name*::
    Required.
    The name of the belief.

*uuid*::
    Optional.
    The UUID of the belief. If not specified it is randomly generated.

*perceptions*::
    Optional.
    A map from behaviour uuids (see behaviours.json(5)) to perceptions.

    This is the amount that a person performing the behaviour can be assumed to be driven by the behaviour.

    This must be between -1 and +1.