= concept(1)
Robert Greener
v0.3.0-SNAPSHOT
:doctype: manpage
:manmanual: Concepts Manual
:mansource: behaviours
:man-linkstyle: pass:[blue R < >]

== Name

concept - Run a simulation which explores how beliefs and behaviours spread.

== Synopsis

*concept* [_OPTION_]...

== Options

*-V, --version*::
    Print the version information.

*-h, --help*::
    Print the help information.

*-L, --copyright*::
    Print the copyright information and exit.

*-b, --behaviours*=_file_::
    The behaviours config JSON file, see behaviours.json(5).

*-c, --beliefs*=_file_::
    The beliefs config JSON file, see beliefs.json(5).

*-a, --agents*=_file_::
    The agents config JSON file, see agents.json(5).

*-p, --performance-relationships*=_file_::
    The performance relationships config JSON file, see prs.json(5).

*-o, --output*=__file_::
    The output file, storing the mutated agents.json(5).

*-s, --start*=_integer_::
    The simulation start time.

*-e, --end*=_integer_::
    The simulation end time.

== Resources

*Source code hosting*: https://github.com/0xr0bert/concept

== Copying

Copyright (c) 2022, Robert Greener

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
