= relationships.json(5)
Robert Greener
v0.0.1
:doctype: manpage
:manmanual: Concepts Manual
:mansource: relationships
:man-linkstyle: pass:[blue R < >]

== Name

relationships.json - A json file used for describing the relationships between beliefs used in concept(1).

== Description

The relationships.json(5) configuration file specifies the relationships between beliefs which are used in the concept(1) simulation.

An example relationships.json.example should have been provided with his application.

This is a valid json file.

The file is a takes the format of repeated entries of:

----
{
  "belief1Uuid": "907f0d52-c578-4256-a419-fcc51a1ad959",
  "belief2Uuid": "ac5f1895-9e6d-4c9e-99ae-66472eee4482",
  "value": 0.4
}
----

inside a json array.

== Fields

Each entry in the top-level array contains `belief1Uuid`, `belief2Uuid`, and `value`

*belief1Uuid*::
    Required.
    The UUID of the first belief.

    This must be present in beliefs.json(5).

*belief2Uuid*::
    Required.
    The UUID of the second belief.

    This must be present in beliefs.json(5).

*value*::
    Required.
    The value of the relationship.

    This is the amount another belief (`b2`) can be deemed compatible with holding this belief (`b1`), given that you already hold `b1`.

    This must be between -1 and +1.